apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nas-txp-hellolinux-images
spec:
  capacity:
    storage: 10Gi
  storageClassName: nas
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "alicloud/nas"
    options:
      mode: '766'
      modeType: recursive
      server: "1c16a4bb1d-hat25.cn-beijing.nas.aliyuncs.com"
      path: "/txp/hellolinux/images"
      vers: "3"
      options: "nolock,tcp,noresvport"
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-txp-hellolinux-images
spec:
  storageClassName: nas
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nas-txp-hellolinux-files
spec:
  capacity:
    storage: 10Gi
  storageClassName: nas
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "alicloud/nas"
    options:
      mode: '766'
      modeType: recursive
      server: "1c16a4bb1d-hat25.cn-beijing.nas.aliyuncs.com"
      path: "/txp/hellolinux/files"
      vers: "3"
      options: "nolock,tcp,noresvport"
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-txp-hellolinux-files
spec:
  storageClassName: nas
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

      
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nas-txp-hellolinux-themes
spec:
  capacity:
    storage: 1Gi
  storageClassName: nas
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "alicloud/nas"
    options:
      mode: '766'
      modeType: recursive
      server: "1c16a4bb1d-hat25.cn-beijing.nas.aliyuncs.com"
      path: "/txp/hellolinux/themes"
      vers: "3"
      options: "nolock,tcp,noresvport"
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-txp-hellolinux-themes
spec:
  storageClassName: nas
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

      
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nas-txp-hellolinux-plugins
spec:
  capacity:
    storage: 1Gi
  storageClassName: nas
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "alicloud/nas"
    options:
      mode: '766'
      modeType: recursive
      server: "1c16a4bb1d-hat25.cn-beijing.nas.aliyuncs.com"
      path: "/txp/hellolinux/plugins"
      vers: "3"
      options: "nolock,tcp,noresvport"
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-txp-hellolinux-plugins
spec:
  storageClassName: nas
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
